### ISSUE TITLE
customHide参数的判断时机可以适当提前

### ISSUE THREAD

**Issue by Nick-Nice** [vadxq/vite-plugin-vconsole#20]
我认为传递了customHide参数通常是不需要生成vconsole的，也就是不调用new VConsole，而不是通过使用vConsole.destroy()去销毁
当前vconsole使用destory会造成后续报错
Uncaught TypeError: Cannot read properties of undefined (reading 'update')
    at u2 (vconsole.min.js:10:91405)
    at e2._flushLogs (vconsole.min.js:10:91641)
    at vconsole.min.js:10:91147

**Comment by vadxq** [comment]
好！我研究一下！非常感谢建议！

**Comment by a982246809** [comment]
这个问题还没修复吗
